
export const opcionesData = [
    {
        idPregunta: 2,
        idRespuesta: 1,
        respuestaDescripcion: 'No poseo conocimiento.',
        valor: 0.08,
    },
    {
        idPregunta: 2,
        idRespuesta: 2,
        respuestaDescripcion: 'Tengo conocimientos básicos acerca de las distintas alternativas de inversión.',
        valor: 0.16,
    },
    {
        idPregunta: 2,
        idRespuesta: 3,
        respuestaDescripcion: 'Tengo conocimientos acerca del riesgo y rentabilidad potencial de los distintos instrumentos financieros.',
        valor: 0.24,
    },
    {
        idPregunta: 2,
        idRespuesta: 4,
        respuestaDescripcion: 'Poseo un profundo conocimiento acerca de las distintas alternativas de inversión (Profesional en Finanzas).',
        valor: 0.32,
    },
    {
        idPregunta: 3,
        idRespuesta: 1,
        respuestaDescripcion: 'Ninguna.',
        valor: 0.1,
    },
    {
        idPregunta: 3,
        idRespuesta: 2,
        respuestaDescripcion: 'Baja.',
        valor: 0.2,
    },
    {
        idPregunta: 3,
        idRespuesta: 3,
        respuestaDescripcion: 'Media.',
        valor: 0.3,
    },
    {
        idPregunta: 3,
        idRespuesta: 4,
        respuestaDescripcion: 'Alta.',
        valor: 0.4,
    },
    {
        idPregunta: 4,
        idRespuesta: 1,
        respuestaDescripcion: 'Menos del 5%.',
        valor: 0.05,
    },
    {
        idPregunta: 4,
        idRespuesta: 2,
        respuestaDescripcion: 'Entre el 5% y el 20%.',
        valor: 0.1,
    },
    {
        idPregunta: 4,
        idRespuesta: 3,
        respuestaDescripcion: 'Entre el 21% y el 50%.',
        valor: 0.15,
    },
    {
        idPregunta: 4,
        idRespuesta: 4,
        respuestaDescripcion: 'Más del 50%.',
        valor: 0.2,
    },
    {
        idPregunta: 5,
        idRespuesta: 1,
        respuestaDescripcion: 'Menos del 25%.',
        valor: 0.05,
    },
    {
        idPregunta: 5,
        idRespuesta: 2,
        respuestaDescripcion: 'Entre el 25% y el 40%.',
        valor: 0.1,
    },
    {
        idPregunta: 5,
        idRespuesta: 3,
        respuestaDescripcion: 'Entre el 41% y el 65%.',
        valor: 0.15,
    },
    {
        idPregunta: 5,
        idRespuesta: 4,
        respuestaDescripcion: 'Más del 65%.',
        valor: 0.2,
    },
    {
        idPregunta: 6,
        idRespuesta: 1,
        respuestaDescripcion: 'Menos de 180 días.',
        valor: 0.15,
    },
    {
        idPregunta: 6,
        idRespuesta: 2,
        respuestaDescripcion: 'Entre 180 días y 1 año.',
        valor: 0.3,
    },
    {
        idPregunta: 6,
        idRespuesta: 3,
        respuestaDescripcion: 'De 1 a 2 años.',
        valor: 0.45,
    },
    {
        idPregunta: 6,
        idRespuesta: 4,
        respuestaDescripcion: 'Más de 2 años.',
        valor: 0.6,
    },
    {
        idPregunta: 7,
        idRespuesta: 1,
        respuestaDescripcion: 'Preservar el dinero que se invirtió con una rentabilidad mínima.',
        valor: 0.25,
    },
    {
        idPregunta: 7,
        idRespuesta: 2,
        respuestaDescripcion: 'Tener una ganancia apenas superior a la de un plazo fijo, aunque esté sujeta a una variación mínima del mercado.',
        valor: 0.5,
    },
    {
        idPregunta: 7,
        idRespuesta: 3,
        respuestaDescripcion: 'Obtener una ganancia significativa, corriendo el riesgo de perder más de la mitad de la inversión inicial.',
        valor: 0.75,
    },
    {
        idPregunta: 8,
        idRespuesta: 1,
        respuestaDescripcion: 'Entre 0% y el 5%.',
        valor: 0.12,
    },
    {
        idPregunta: 8,
        idRespuesta: 2,
        respuestaDescripcion: 'Entre el 5% y el 15%.',
        valor: 0.24,
    },
    {
        idPregunta: 8,
        idRespuesta: 3,
        respuestaDescripcion: 'Entre 15% y 30%.',
        valor: 0.36,
    },
    {
        idPregunta: 8,
        idRespuesta: 4,
        respuestaDescripcion: 'Más de 30%.',
        valor: 0.48,
    },
    {
        idPregunta: 9,
        idRespuesta: 1,
        respuestaDescripcion: 'Vendería la inversión para evitar una mayor pérdida.',
        valor: 0.15,
    },
    {
        idPregunta: 9,
        idRespuesta: 2,
        respuestaDescripcion: 'Transferiría algunos activos a inversiones de menor riesgo.',
        valor: 0.3,
    },
    {
        idPregunta: 9,
        idRespuesta: 3,
        respuestaDescripcion: 'Esperaría que la inversión recupere su valor inicial.',
        valor: 0.45,
    },
    {
        idPregunta: 9,
        idRespuesta: 4,
        respuestaDescripcion: 'Compraría una mayor cantidad aprovechando que el precio actual es menor al que había pagado inicialmente.',
        valor: 0.6,
    },
    {
        idPregunta: 1,
        idRespuesta: 1,
        respuestaDescripcion: 'Menos de 25 años.',
        valor: 0.2,
    },
    {
        idPregunta: 1,
        idRespuesta: 2,
        respuestaDescripcion: 'De 25 a 35 años.',
        valor: 0.15,
    },
    {
        idPregunta: 1,
        idRespuesta: 3,
        respuestaDescripcion: 'De 36 a 55 años.',
        valor: 0.1,
    },
    {
        idPregunta: 1,
        idRespuesta: 4,
        respuestaDescripcion: 'De 56 años o más.',
        valor: 0.05,
    },
];
